// `.env.json` is generated by the `npm run build` command
import * as env from './.env.json';

export const environment = {
  production: true,
  version: '(prod)',
  serverUrl: 'http://localhost:48748/',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'ua-RU',
    'en-US',
    'fr-FR',
    'es-ES',
    'ru-RU'
  ]
};
